package:
  name: bp-help
  version: "0.3"

source:
  path: ../

requirements:
  build:
    - python
  run:
    - python #>=3.9, <=3.11
    - pygments
    - textual
    - rich
    - art

channels:
  - defaults
  - conda-forge
  - sepandhaghighi

about:
  home: https://github.com/kaspermunch/bp-help
  license: MIT

build:
  script: python -m pip install . -vv
  noarch: python

test:
  imports:
    - bp-help

