{% set version = "0.7" %}

package:
  name: bp-help
  version: {{ version }}

source:
  git_url: https://github.com/kaspermunch/bp-help.git

build:
  noarch: python
  number: 0
  # script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - print-steps = bp_help.print_steps:run_student_file
    - myiagi = bp_help.text_gui:run

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bp_help

about:
  home: https://github.com/kaspermunch/bp-help.git
  license: MIT
  summary: 'summary'
  description: |
    Description.


# package:
#   name: bp-help
#   version: "0.3"

# source:
#   path: ../

# requirements:
#   build:
#     - python
#   run:
#     - python #>=3.9, <=3.11
#     - pygments
#     - textual
#     - rich
#     - art

# channels:
#   - defaults
#   - conda-forge
#   - sepandhaghighi

# about:
#   home: https://github.com/kaspermunch/bp-help
#   license: MIT

# build:
#   script: python -m pip install . -vv
#   noarch: python

# test:
#   imports:
#     - bp-help

